### ISSUE TITLE
Help to build openframeworksLib -beginner-

### ISSUE THREAD

**Issue by mcpoieses** [liquidzym/openFrameworks#10]
Hi liquidzym, I'm trying to use VS2013 and it failed because:
Error	1	error C2440: '=' : cannot convert from 'ofPtr<ofGLProgrammableRenderer>' to 'bool'	
C:\Users\mc_000\Documents\openFrameworks-VS2013\libs\openFrameworks\gl\ofVbo.cpp	330	1	openframeworksLib

and the second:
Error	2	error LNK1104: cannot open file 'C:\Users\mc_000\Documents\openFrameworks-VS2013\libs\openFrameworksCompiled\lib\vs\openframeworksLibDebug.lib'	
C:\Users\mc_000\Documents\openFrameworks-VS2013\addons\ofxRSSDK\example-pointcloud\LINK	example-pointcloud

Could you help me to solve this problem?
Thanks in advance!
mariana

**Comment by liquidzym** [comment]
just Uncommenting the "// || glewIsSupported" part of the line will compile
https://github.com/liquidzym/openFrameworks/issues/5

**Comment by mcpoieses** [comment]
Thank you!!
It works!
