### ISSUE TITLE
missing .dlls 64 bit

### ISSUE THREAD

**Issue by dfamil** [liquidzym/openFrameworks#9]
hi

i am working with the kinectv2  and your version does not create the 64bit of a series of .dlls  i able to buiild a freeimage .dll 64bit but once i added it it needed fmodex and in looking on the web it may also need freetype and maybe more i don't know yet.

**Comment by liquidzym** [comment]
hey,if you're looking for 64 bit OF
here it is https://github.com/liquidzym/openframeworks_X64
